'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Orders', [{"id":1,"user_id":17,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":2,"user_id":1,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":3,"user_id":9,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":4,"user_id":14,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":5,"user_id":38,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":6,"user_id":23,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":7,"user_id":27,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":8,"user_id":44,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":9,"user_id":29,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":10,"user_id":3,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":11,"user_id":45,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":12,"user_id":6,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":13,"user_id":4,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":14,"user_id":37,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":15,"user_id":41,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":16,"user_id":2,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":17,"user_id":47,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":18,"user_id":5,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":19,"user_id":12,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":20,"user_id":14,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":21,"user_id":6,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":22,"user_id":16,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":23,"user_id":27,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":24,"user_id":36,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":25,"user_id":40,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":26,"user_id":27,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":27,"user_id":2,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":28,"user_id":38,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":29,"user_id":14,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":30,"user_id":10,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":31,"user_id":5,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":32,"user_id":14,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":33,"user_id":3,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":34,"user_id":15,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":35,"user_id":32,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":36,"user_id":9,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":37,"user_id":4,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":38,"user_id":28,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":39,"user_id":19,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":40,"user_id":34,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":41,"user_id":17,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":42,"user_id":39,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":43,"user_id":25,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":44,"user_id":7,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":45,"user_id":45,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":46,"user_id":20,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":47,"user_id":16,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":48,"user_id":5,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":49,"user_id":33,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":50,"user_id":26,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":51,"user_id":46,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":52,"user_id":23,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":53,"user_id":39,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":54,"user_id":40,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":55,"user_id":47,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":56,"user_id":26,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":57,"user_id":2,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":58,"user_id":40,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":59,"user_id":13,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":60,"user_id":21,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":61,"user_id":36,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":62,"user_id":23,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":63,"user_id":17,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":64,"user_id":31,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":65,"user_id":46,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":66,"user_id":33,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":67,"user_id":8,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":68,"user_id":2,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":69,"user_id":39,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":70,"user_id":19,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":71,"user_id":14,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":72,"user_id":5,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":73,"user_id":22,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":74,"user_id":47,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":75,"user_id":26,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":76,"user_id":34,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":77,"user_id":25,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":78,"user_id":4,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":79,"user_id":25,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":80,"user_id":33,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":81,"user_id":25,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":82,"user_id":1,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":83,"user_id":29,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":84,"user_id":43,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":85,"user_id":6,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":86,"user_id":46,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":87,"user_id":27,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":88,"user_id":38,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":89,"user_id":25,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":90,"user_id":13,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":91,"user_id":34,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":92,"user_id":38,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":93,"user_id":32,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":94,"user_id":35,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":95,"user_id":9,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":96,"user_id":9,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":97,"user_id":34,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":98,"user_id":10,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":99,"user_id":4,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()},
    {"id":100,"user_id":21,"payment_amount":11.99,"order_date":new Date(),"createdAt":new Date(),"updatedAt":new Date()}], {});
  },

  async down (queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Orders', null, {});
  }
};
